### ISSUE TITLE
Multiple Filters on Websocket

### ISSUE THREAD

**Issue by ericjohnson97** [mavlink/mavlink2rest#100]
Is mavlink to rest setup to accept multiple filters or is it just one message per websocket stream? 

I have tried this
```
"ws://192.168.1.222:6040/ws/mavlink?filter=LOCAL_POSITION_NED,ATTITUDE
```
but that doesn't seem to work

**Comment by patrickelectric** [comment]
> Is mavlink to rest setup to accept multiple filters or is it just one message per websocket stream?
> 
> I have tried this
> 
> ```
> "ws://192.168.1.222:6040/ws/mavlink?filter=LOCAL_POSITION_NED,ATTITUDE
> ```
> 
> but that doesn't seem to work

Hi @ericjohnson97, you should be using a regex: "LOCAL_POSITION_NED|ATTITUDE"
As explained here: https://github.com/mavlink/mavlink2rest?tab=readme-ov-file#websocket

**Comment by ericjohnson97** [comment]
Forgot to respond to this. 

Yep it is regex! I need to read more carefully 🤦‍♂️
