### ISSUE TITLE
Unable to ARM the drone 

### ISSUE THREAD

**Issue by sundaram123krishnan** [mavlink/mavlink2rest#101]
I am able to send POST request,
![Screenshot from 2024-04-26 22-25-29](https://github.com/mavlink/mavlink2rest/assets/104441812/8f169851-6457-4cb6-8430-dcad80b2d5ae)
i can see the output as well, 
But the drone is not getting armed

**Comment by patrickelectric** [comment]
Did you check this example ?

https://github.com/mavlink/mavlink2rest?tab=readme-ov-file#request-vehicle-to-be-armed

**Comment by sundaram123krishnan** [comment]
yaa i did referred to that example only,
this is the request i sent
curl --request POST http://172.22.254.115:8088/v1/mavlink -H "Content-Type: application/json" --data \
'{
  "header": {
    "system_id": 1,
    "component_id": 1,
    "sequence": 0
  },
  "message": {
    "type":"COMMAND_LONG",
    "param1": 1.0,
    "param2": 0.0,"param3":0.0,"param4":0.0,"param5":0.0,"param6":0.0,"param7":0.0,
    "command": {
      "type": "MAV_CMD_COMPONENT_ARM_DISARM"
    },
    "target_system": 1,
    "target_component": 1,
    "confirmation": 1
  }
}' --verbose

**Comment by sundaram123krishnan** [comment]
Thx for ur kind response, 
it works now
