### ISSUE TITLE
Move to MIT

### ISSUE THREAD

**Issue by patrickelectric** [mavlink/mavlink2rest#75]
Hi, I want to move the project to MIT to be more accessible.
If you are tagged here is because you are one the developers of the project. Please confirm that you are ok with the license change.

- [x] @rotu
- [x] @noahbliss
- [x] @zhiburt
- [x] @joaoantoniocardoso
- [x] @Williangalvani

**Comment by Williangalvani** [comment]
I"m ok with it!

**Comment by joaoantoniocardoso** [comment]
@patrickelectric I agree :)

**Comment by noahbliss** [comment]
Fine.

**Comment by rotu** [comment]
And my axe! (go for it!)

**Comment by zhiburt** [comment]
👍

**Comment by patrickelectric** [comment]
Thank you very much!

**Comment by mrpollo** [comment]
Thanks, everyone.
