### ISSUE TITLE
COMMAND_LONG

### ISSUE THREAD

**Issue by 741736507** [mavlink/mavlink2rest#81]
The server reported an error when sending the command, and the response was too slow. For example, the server reports an error and the response times out when a command is issued to remove the UAV from defense.

 
![image](https://github.com/mavlink/mavlink2rest/assets/20473900/bed826f7-d655-4a81-b1f3-e01b54a0b412)
![image](https://github.com/mavlink/mavlink2rest/assets/20473900/f5adfe3c-4dc9-46a5-8e28-1b242424f2af)

**Comment by patrickelectric** [comment]
please provide the message that you sending in a curl or javascript example.
