### ISSUE TITLE
Unable to receive data from mavproxy

### ISSUE THREAD

**Issue by sundaram123krishnan** [mavlink/mavlink2rest#97]
![Screenshot from 2024-03-08 17-50-21](https://github.com/mavlink/mavlink2rest/assets/104441812/cb8aa540-6bd5-454c-8e79-7fe742d5f522)
![Screenshot from 2024-03-08 17-55-53](https://github.com/mavlink/mavlink2rest/assets/104441812/fe8a8f3a-2937-42ad-a568-b3849fdc9a34)

Always giving None

**Comment by sundaram123krishnan** [comment]
Pls help someone

**Comment by patrickelectric** [comment]
put udpin on the output of mavproxy

**Comment by patrickelectric** [comment]
Are you running mavlink v2 or v1 ? try adding `--mavlink 1` on the command line
